# NOTE: You should only really need to change any of this file if things are going wrong.

# Set to true to log messages to the mod engine log when attempting to upgrade weapons.
log_debug_messages = false

# Set to true to allow a debug window overlay indicating what the current known upgrade level is, how many weapons have been upgraded this session, etc.
# The window will start out hidden, with an extra grace submenu option appearing that allows the window visibility to be toggled.
allow_debug_window_overlay = false

# Some overhaul mods (currently supports Reborn) may change the upgrade system, so auto-upgrading doesn't work correctly.
# This will check certain values to make sure that you are running Reborn and patch in-memory values when necessary.
# Set this to false if things are breaking and you're not using Reborn.
patch_weapon_reinforcements = true

# Extra config for text and menus.
[extra_config]
  # Text that can add or override Event Text For Talk content.
  [extra_config.extra_text]
    ## Text ids ending with 1XXX, because they don't need to be in a saved id range, and any 1XXX is invalid for flags.
    event_text_for_talk = [
      { text_id = 1061471000, text = "Absolute Weapon Tools" },
      { text_id = 1061471001, text = "Upgrade all held weapons to max achieved so far" },
      { text_id = 1061471002, text = "Show/hide upgrade stats" },
      { text_id = 1061471003, text = "This will update all weapons in your inventory to the max achieved so far. Are you sure?" },
    ]

  # Options and submenus to add to the grace menu
  [extra_config.extra_menu]
    # Base id for newly creates states and events so that they don't clash with existing ones.
    # Only change this if menu items aren't appearing, or you are having compatibility issues with other mods.
    base_state_and_event_id = 0xFFFF

    # Grace menu items and submenus.
    # The double [[ and ]] below indicates that this block can be repeated to add new menu and submenu items.
    [[extra_config.extra_menu.extra_menu_items]]
      # An optional flag id that will show/hide the grace menu item.
      #   Any valid flag id - grace menu item is only shown when the flag is set. 0XXX, 4XXX, 7XXX, 8XXX, or 9XXX for saved flags.
      #   0 (or absent) - grace menu item is shown always
      show_on_event_flag_id = 0

      # The text id from Event Text For Talk, or added to extra_text above, that will appear as the new option in the grace menu.
      menu_item_text_id = 1061471000

      # The options in the submenu
      #   text_id - from Event Text For Talk, or added to extra_text above.
      #   select_flag_id - set on select. 0XXX, 4XXX, 7XXX, 8XXX, or 9XXX for saved flags. 2XXX or 5XXX for temporary.
      #   confirmation_text_id - An optional text id that will show in a confirmation dialog before setting the flag.
      #   show_on_event_flag_id - An optional flag id that will show/hide the grace menu item.
      #     Any valid flag id - item is only shown when the flag is set. 0XXX, 4XXX, 7XXX, 8XXX, or 9XXX for saved flags.
      #     0 (or absent) - item is shown always
      sub_menu_item_config = [
        { text_id = 1061471001, select_flag_id = 1061475001, confirmation_text_id = 1061471003 },
        { text_id = 1061471002, select_flag_id = 1061475002, show_on_event_flag_id = 1061470002 },
      ]